apiVersion: v1
appVersion: 6.4.1
description: A Helm chart to collect Kubernetes logs with filebeat
home: https://www.elastic.co/products/beats/filebeat
icon: https://www.elastic.co/assets/blt47799dcdcf08438d/logo-elastic-beats-lt.svg
maintainers:
- email: pete.brown@powerhrg.com
  name: rendhalver
- email: shane.starcher@gmail.com
  name: sstarcher
name: filebeat
sources:
- https://www.elastic.co/guide/en/beats/filebeat/current/index.html
version: 1.0.2
