# Default values for meep-tc-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
serviceAccount: meep-tc-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP

image:
  repository: meep-tc-engine
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  targetPort: 80
  nodePort: 30003

codecov:
  enabled: false
  
meepOrigin: core
