apiVersion: v1
appVersion: "1.0"
description: A Helm chart to export the metrics from couchdb in Prometheus format.
home: https://github.com/gesellix/couchdb-prometheus-exporter
keywords:
- couchdb-exporter
maintainers:
- email: github.gkarthiks@gmail.com
  name: gkarthiks
name: prometheus-couchdb-exporter
sources:
- https://github.com/gesellix/couchdb-prometheus-exporter
version: 0.2.0
