---

- name: Assert OS is Ubuntu 18.04
  assert:
    that:
      - ansible_distribution == "{{ ubuntu_dist }}"
      - ansible_distribution_major_version == "{{ ubuntu_dist_major }}"
      - ansible_distribution_version == "{{ ubuntu_dist_version }}"
    quiet: yes

- name: Gather package facts
  package_facts:
    manager: apt

- name: Get currently installed Docker version
  set_fact:
    installed_docker_version: "{{ ansible_facts.packages['docker-ce'][0].version }}"
  when:
    - "'docker-ce' in ansible_facts.packages"

- name: Assert currently installed Docker version is supported
  assert:
    that:
      - installed_docker_version is match("{{ docker_version }}*")
    quiet: yes
  when:
    - installed_docker_version is defined

- name: Install Docker
  include_tasks:
    file: install.yml
  when:
    - installed_docker_version is undefined