apiVersion: v1
name: postgis
version: 8.9.5
appVersion: 11.7.0
description: Chart for PostGIS, a spatial database extender for PostgreSQL object-relational database
keywords:
  - postgresql
  - postgres
  - database
  - sql
  - replication
  - cluster
  - postgis
home: https://postgis.net/
sources:
  - https://github.com/postgis/postgis
