{{- if .Values.codecov.enabled}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: meep-gis-engine-codecov-pv
spec:
  storageClassName: meep-gis-engine-codecov-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/englab/.meep/codecov/meep-gis-engine"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: meep-gis-engine-codecov-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meep-gis-engine-codecov-pvc
spec:
  storageClassName: meep-gis-engine-codecov-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- end}}
