client:
  replicas: 1

indices.fielddata.cache.size: 20%
search.max_bucket: 1000

initImage:
  pullPolicy: IfNotPresent

image:
  tag: 6.4.3
  pullPolicy: IfNotPresent

data:
  persistence:
    storageClass: meep-pv-es-data
  replicas: 1
  exposeHttp: true
  heapSize: 1g

master:
  persistence:
    storageClass: meep-pv-es-master
  replicas: 2
  exposeHttp: true
