apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "meep-webhook.fullname" . }}
webhooks:
  - name: {{ .Values.webhook.name }}
    clientConfig:
      service:
        name: {{ template "meep-webhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: {{ .Values.webhook.cabundle }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments", "statefulsets"]
