apiVersion: v1
appVersion: 2.7.1
description: A Helm chart for Docker Registry
home: https://hub.docker.com/_/registry/
icon: https://hub.docker.com/public/images/logos/mini-logo.svg
maintainers:
- email: jpds@protonmail.com
  name: jpds
- email: pete.brown@powerhrg.com
  name: rendhalver
name: docker-registry
sources:
- https://github.com/docker/distribution-library-image
version: 1.9.2
