# Default values for meep-ctrl-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
serviceAccount: meep-ctrl-engine

deployment:
  replicas: 1
  port: 80
  protocol: TCP

image:
  repository: meep-ctrl-engine
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  targetPort: 80
  nodePort: 30000

codecov:
  enabled: false

meepOrigin: core
